### ISSUE TITLE
Facebook Login 

### ISSUE THREAD

**Issue by marcocast** [cipto-hd/angularjsfire-with-reg-confirmation#2]
Hi,

When I try to login with facebook I always get a pop up error message saying : 

"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

It works with other social login like twitter. I think there is something in the Valid OAuth redirect URIs that Facebook doesn't like. My firebase is called marcocast so I put : 

https://auth.firebase.com/v2/marcocast/auth/facebook/callback

When I try with other examples (like firefeed), the facebook login works.

Any idea why? Is it possible that is because there is a # in the url (https://marcocast.firebaseapp.com/#/home)?

Thanks

**Comment by cipto-hd** [comment]
make sure you make fb app and setup correctly (https://www.firebase.com/docs/web/guide/login/facebook.html)

check this http://stackoverflow.com/a/23233257
